services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - ENVIRONMENT=development
      - INSTANCE=dev
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      # Azure SSO Configuration (Frontend)
      - NEXT_PUBLIC_AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
      - NEXT_PUBLIC_AZURE_TENANT_ID=${AZURE_TENANT_ID:-}
      - NEXT_PUBLIC_AZURE_REDIRECT_URI=${AZURE_REDIRECT_URI:-http://localhost:3000/authorize}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - SECRET_KEY=development_secret_key
      - INSTANCE=dev
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/uru_chatbot
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
      - ENVIRONMENT=development
      # Azure SSO Configuration (Backend)
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET:-}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID:-}
      - AZURE_REDIRECT_URI=${AZURE_REDIRECT_URI:-http://localhost:3000/authorize}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uru_chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
  app_data:

networks:
  app-network:
    driver: bridge
